### ISSUE TITLE
Making attractive navbar(improvement)

### ISSUE THREAD

**Issue by kumarishalini6** [ChetnaNSharma/Alumni-Connect#48] opened 2021-04-08 12:00 UTC
I want to redesign navbar , making it more attractive which is suitable according to project . i want to work on this issue under GSSoC'21 participant.
And also navbar is not working properly.

**Comment by yash982000** [comment] 2021-04-13 05:02
> I want to redesign navbar , making it more attractive which is suitable according to project . i want to work on this issue under GSSoC'21 participant.
> And also navbar is not working properly.

Sure, you can propose the changes you want.
But, make sure it aligns with the project designs.

**Comment by kumarishalini6** [comment] 2021-04-13 05:25
Thanks for assigning me .
Can you please add labels in this issue

**Comment by yash982000** [comment] 2021-04-13 05:29
> Thanks for assigning me .
> Can you please add labels in this issue

@kumarishalini6 Done. DM me on whatsapp now or discord DM as I won't be able to check regularly here.

**Comment by srrathi** [comment] 2021-05-01 04:55
@yash982000 Can I work on this issue. I'll make the navbar responsive too.

**Comment by yash982000** [comment] 2021-05-03 20:46
> @yash982000 Can I work on this issue. I'll make the navbar responsive too.

@kumarishalini6 @srrathi Can you both please figure out who is active and who will be working?

**Comment by srrathi** [comment] 2021-05-03 21:07
> > @yash982000 Can I work on this issue. I'll make the navbar responsive too.
> 
> @kumarishalini6 @srrathi Can you both please figure out who is active and who will be working?

@kumarishalini6 You raised the issue and you came first to resolve it, If you are active it's allright I"ll search for another issuse for me. If you are inactive or not working in this issue do let me know so that I can start working on it.

**Comment by kumarishalini6** [comment] 2021-05-04 00:15
I have sent PR on this issue and got merged  too.

**Comment by srrathi** [comment] 2021-05-04 11:30
@yash982000 if the issue is resolved, can you please close it.

**Comment by yash982000** [comment] 2021-05-04 12:24
@kumarishalini6 Just try to always reference the issue with linked PR, so that it gets automatically closed.

**Closed as completed by yash982000** 2021-05-04 12:24 UTC
Labels: enhancement, good first issue, GSSoC21, Moderate, Level2
